version: 2.1

orbs:
  android: circleci/android@1.0.3
  maven: circleci/maven@0.0.12

jobs:
  # android-test:
  #   working_directory: ~/repo/App
  #   parameters:
  #     system-image:
  #       type: string
  #       default: system-images;android-30;google_apis;x86
  #   executor:
  #     name: android/android-machine
  #     resource-class: medium
  #   steps:
  #     - checkout
  #     - android/start-emulator-and-run-tests:
  #         test-command: ./gradlew connectedDebugAndroidTest
  #         system-image: << parameters.system-image >>
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always
  #     - store_test_results:
  #         path: ~/test-results
  #     - store_artifacts:
  #         path: ~/test-results/junit

  maven-test:
    working_directory: ~/repo/DBServer
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: ./mvnw clean test

  build:
    working_directory: ~/repo/App
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/repo
      - android/restore-gradle-cache
      - android/restore-build-cache
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  
  release-build:
    working_directory: ~/repo/App
    executor:
      name: android/android-machine
    steps:
      - checkout:
          path: ~/repo
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          # using the command ./gradlew assembleDebug instead of assembleRelease as assembleRelease has issues
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/release/SkyWrite_Build.apk

workflows:  
  build_and_save:
    jobs:
      - maven/test
      - build
      - release-build
